### ISSUE TITLE
@heap/heap-react-native-bridge throws "Parameter specified as non-null is null:" on RN 0.76 on Android

### ISSUE THREAD

**Issue by crrobinson14** [heap/react-native-heap#435]
This seems to work properly on iOS. On Android, using:
- React Native 0.76.1
- @heap/heap-react-native-bridge 0.7.0

```11-01 13:07:36.878   937   981 W unknown:BridgelessReact: ReactHost{0}.getOrCreateDestroyTask()
11-01 13:07:36.878   937   981 W unknown:BridgelessReact: ReactHost{0}.raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "Parameter specified as non-null is null: method io.heap.react.core.HeapReactNativeBridgeModule.handleResult, parameter data")
11-01 13:07:36.878   937   981 E unknown:ReactHost: Unhandled SoftException
11-01 13:07:36.878   937   981 E unknown:ReactHost: com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "Parameter specified as non-null is null: method io.heap.react.core.HeapReactNativeBridgeModule.handleResult, parameter data")
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(ReactHostImpl.java:942)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.ReactHostImpl.getOrCreateDestroyTask(ReactHostImpl.java:1575)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.ReactHostImpl.lambda$destroy$7(ReactHostImpl.java:541)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$uso21_D6dCZdcf-JomVD56kdG4c(Unknown Source:0)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda37.call(D8$$SyntheticClass:0)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.runtime.internal.bolts.Task$2.run(Task.java:240)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at java.lang.Thread.run(Thread.java:1012)
11-01 13:07:36.878   937   981 E unknown:ReactHost: Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method io.heap.react.core.HeapReactNativeBridgeModule.handleResult, parameter data
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at io.heap.react.core.HeapReactNativeBridgeModule.handleResult(Unknown Source:7)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.jni.NativeRunnable.run(Native Method)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at android.os.Handler.handleCallback(Handler.java:959)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at android.os.Looper.loopOnce(Looper.java:232)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at android.os.Looper.loop(Looper.java:317)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
11-01 13:07:36.878   937   981 E unknown:ReactHost: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
```

I assume this has something to do with the new Bridgeless mode in New Architecture particularly due to the reference to `HeapReactNativeBridgeModule.handleResult`.

Do you have a timeline on supporting this yet? We're counting on bringing in a number of RN-core bug fixes and improvements into our app via 0.76 and this appears to be the only module blocking the upgrade.

**Comment by bnickel** [comment]
This issue was resolved in 0.7.1
