### ISSUE TITLE
[Android] Events are not being captured. -> Heap was not configured properly warning in logcat. 

### ISSUE THREAD

**Issue by pachuka** [heap/react-native-heap#5]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 52.93 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
      npm: 6.5.0 - ~/.nvm/versions/node/v11.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native: 0.57.7
```
## Description
Originally tried integration steps in two of my existing projects. Both exhibited same warning/behavior. In-order to isolate the issue:

Created a react-native project following the [build projects w/ Native-code](https://facebook.github.io/react-native/docs/getting-started) for a clean environment.
Then followed steps in readme for Android/iOS integration.
The first time I launch the Android app via react-native when the `Heap.setAppId('app-id')` is called,  I see the following warning/exception:

```
2018-12-21 11:15:58.274 10828-10907/com.heapintegrationtest W/Heap: Could not find BuildConfig
    com.heapanalytics.android.internal.HeapException: Heap was not configured properly. Check logcat for Heap build warnings and resolution steps. (Build Config resource ID = 0.)
        at com.heapanalytics.android.internal.BuildConfigRetrieverImpl.getBuildConfig(BuildConfigRetrieverImpl.java:15)
        at com.heapanalytics.android.internal.AppState.getBuildConfigField(AppState.java:303)
        at com.heapanalytics.android.internal.AppState.getApplicationInfo(AppState.java:252)
        at com.heapanalytics.android.internal.AppState.createInitialUserProperties(AppState.java:143)
        at com.heapanalytics.android.internal.AppState.sendInitialUserProperties(AppState.java:151)
        at com.heapanalytics.android.internal.HeapImpl.unsafeInit(HeapImpl.java:193)
        at com.heapanalytics.android.internal.HeapImpl.init(HeapImpl.java:74)
        at com.heapanalytics.android.internal.HeapImpl.init(HeapImpl.java:58)
        at com.heapanalytics.android.Heap.init(Heap.java:18)
        at com.heapanalytics.reactnative.RNHeapLibraryModule.setAppId(RNHeapLibraryModule.java:35)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by GrandPoohBear** [comment]
@pachuka - thanks for the detailed write-up.  I think I've got a fix for the time being, though it does require some manual configuration change.  I'm about to add this to the docs, let me know if that works for you:

---

If you are seeing runtime warnings at startup mentioning `Heap: Could not find BuildConfig`, add the
following line to the resources section of res/values/strings.xml:
```xml
<string name="com.heapanalytics.android.buildConfigPkgName">com.your_package_name</string>
```
and replace com.your_package_name with the package name from the manifest tag in AndroidManifest.xml.

**Comment by pachuka** [comment]
@GrandPoohBear - that works great, it fixed the warning. Also, I think I figured out why I wasn't seeing events in general for Android. I was expecting to see automatic events for things, but I'm guessing that isn't really supported yet correct? When I call track manually those events show up fine.

Thanks!

**Comment by drob** [comment]
You are correct – right now, this library only supports manual tracking in React Native. It will also include the autocaptured iOS events, and we're working on ways to make those more useful for React Native apps.

We do support [autocapture for Android apps](https://docs.heapanalytics.com/docs/installation#section-installation-instructions) in general, but not yet for Android apps built with React Native. More to come!
